name: "pr_opened"

on:
  pull_request_target:
    types:
      - opened
      - reopened

permissions:
  pull-requests: write
  checks: read

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}

jobs:
  welcome:
    uses: roc-streaming/ci/.github/workflows/pr_check_first.yml@main
    with:
      base-branch: develop

  wait-build:
    runs-on: ubuntu-latest
    steps:
      - uses: poseidon/wait-for-status-checks@v0.6.0
        with:
          interval: 30s
          timeout: 3600s
          token: ${{ github.token }}

  initial-status:
    needs: [wait-build]
    uses: roc-streaming/ci/.github/workflows/pr_status_detect.yml@main

  check-contrib:
    uses: roc-streaming/ci/.github/workflows/pr_check_contrib.yml@main

  check-issue:
    uses: roc-streaming/ci/.github/workflows/pr_check_issue.yml@main

  check-branch:
    uses: roc-streaming/ci/.github/workflows/pr_check_branch.yml@main
    with:
      base-branch: develop
