name: "pr_opened"

on:
  pull_request_target:
    types:
      - opened

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}

jobs:
  check-ready:
    runs-on: ubuntu-latest
    steps:
      - uses: andymckay/labeler@1.0.4
        if: github.event.pull_request.draft == true
        with:
          add-labels: 'work in progress'

      - uses: andymckay/labeler@1.0.4
        if: tojson(github.event.pull_request.requested_reviewers) != '[]'
        with:
          add-labels: 'ready for review'

  check-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check issue
        id: issue
        run: |
          echo url=$(scripts/pr.py show ${{ github.event.pull_request.number }} --json --no-git \
            | jq -r .issue.url) >> "$GITHUB_OUTPUT"
        env:
         GH_TOKEN: ${{ secrets.github_token }}

      - name: Post Comment
        if: |
          steps.issue.outputs.url == '' ||
          steps.issue.outputs.url == 'null'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ":robot: Upon creation, pull request description does not have a link to an issue.
            If there is a related issue, please add it to the description
            using any of the [supported formats](https://docs.github.com/en/get-started/\
            writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls)."
